import type { Item, User } from '@/types';

export const mockUsers: User[] = [
  {
    id: 'user-1',
    name: 'Alice',
    avatarUrl: 'https://placehold.co/100x100.png',
    points: 150,
  },
  {
    id: 'user-2',
    name: 'Bob',
    avatarUrl: 'https://placehold.co/100x100.png',
    points: 200,
  },
];

export const mockItems: Item[] = [
  {
    id: 'item-1',
    title: 'Vintage Denim Jacket',
    description: 'A classic 90s denim jacket, slightly oversized fit. Perfect for all seasons. Barely worn.',
    images: ['https://placehold.co/600x600.png', 'https://placehold.co/600x600.png'],
    category: 'Outerwear',
    size: 'M',
    condition: 'Like New',
    tags: ['denim', 'vintage', '90s', 'jacket'],
    points: 80,
    status: 'Available',
    userId: 'user-1',
    user: mockUsers[0],
  },
  {
    id: 'item-2',
    title: 'Floral Summer Dress',
    description: 'Light and airy floral dress. Great for summer parties or a casual day out. Worn a few times, in great condition.',
    images: ['https://placehold.co/600x600.png'],
    category: 'Dresses',
    size: 'S',
    condition: 'Good',
    tags: ['floral', 'summer', 'dress', 'casual'],
    points: 60,
    status: 'Available',
    userId: 'user-2',
    user: mockUsers[1],
  },
  {
    id: 'item-3',
    title: 'Cozy Knit Sweater',
    description: 'A very comfortable and warm knit sweater. Perfect for cold days. 100% wool.',
    images: ['https://placehold.co/600x600.png'],
    category: 'Tops',
    size: 'L',
    condition: 'New',
    tags: ['sweater', 'cozy', 'wool', 'winter'],
    points: 100,
    status: 'Available',
    userId: 'user-1',
    user: mockUsers[0],
  },
  {
    id: 'item-4',
    title: 'Black Skinny Jeans',
    description: 'Classic black skinny jeans, very versatile. A wardrobe staple.',
    images: ['https://placehold.co/600x600.png'],
    category: 'Bottoms',
    size: '32/32',
    condition: 'Fair',
    tags: ['jeans', 'black', 'skinny'],
    points: 30,
    status: 'Swapped',
    userId: 'user-2',
    user: mockUsers[1],
  },
    {
    id: 'item-5',
    title: 'Leather Ankle Boots',
    description: 'Stylish and durable leather boots. Great for fall and winter outfits.',
    images: ['https://placehold.co/600x600.png'],
    category: 'Shoes',
    size: '8',
    condition: 'Good',
    tags: ['boots', 'leather', 'shoes'],
    points: 90,
    status: 'Available',
    userId: 'user-1',
    user: mockUsers[0],
  },
  {
    id: 'item-6',
    title: 'Silk Scarf',
    description: 'A beautiful silk scarf with a unique pattern. Can be used as a neck scarf or a bag accessory.',
    images: ['https://placehold.co/600x600.png'],
    category: 'Accessories',
    size: 'One Size',
    condition: 'Like New',
    tags: ['scarf', 'silk', 'accessory', 'pattern'],
    points: 40,
    status: 'Available',
    userId: 'user-2',
    user: mockUsers[1],
  },
];

export const mockSwaps = [
  {
    id: 'swap-1',
    itemOffered: mockItems[0],
    itemRequested: mockItems[1],
    status: 'Ongoing',
    fromUser: mockUsers[0],
    toUser: mockUsers[1],
  },
  {
    id: 'swap-2',
    itemOffered: mockItems[3],
    itemRequested: mockItems[2],
    status: 'Completed',
    fromUser: mockUsers[1],
    toUser: mockUsers[0],
  },
];
